### ISSUE TITLE
shareButtons - no work

### ISSUE THREAD

**Issue by VadymVolos** [web-xaser/postium#2]
shareButtons - no work

**Comment by web-xaser** [comment]
Hello @VadymVolos. In [latest commit](https://github.com/web-xaser/postium/commit/8baf37e1453ef37590d74614cb011893c1ee7d20) I added share links. Check it now!

**Comment by VadymVolos** [comment]
Working!

But when push share on facebook
the picture is not mine
![2016-04-12](https://cloud.githubusercontent.com/assets/12669290/14450642/f87dcc4c-0088-11e6-93d2-b8d2ed989d39.png)


**Also I do not like button "Squirt it"**

**Comment by web-xaser** [comment]
@VadymVolos, Facebook [takes](https://developers.facebook.com/docs/sharing/webmasters#markup) title, description & image from Open Graph meta-tags. So he will share first image that he find in post (not all blog). You can check it in Facebook [URL Debugger](https://developers.facebook.com/tools/debug/).

If you don't like squirt button, just delete [this line](https://github.com/web-xaser/postium/blob/master/template.xml#L652).

**Comment by VadymVolos** [comment]
Ok. Thanks!
