### ISSUE TITLE
В шапке под названием выводится текст Технологии Blogger.

### ISSUE THREAD

**Issue by VadymVolos** [web-xaser/postium#3]
Привет Павел!

Вообщем в шапке под названием выводится текст "Технологии Blogger",
со ссылкой. Этот текст убрать не получается.

Я так понимаю он должен быть в подвале, в копирайте, но на данный момент он в шапке.

===

Еще один момент, если зайти в админку, настройки - описание
то когда вписать описание для сайта, сохранить, проверить, в шапке оно не отображается.

`<p class="description"><span> описание</span></p>`

**Comment by VadymVolos** [comment]
Я заливал шаблон через кнопку "Резервное копирование и восстановление"

Но сейчас я попробовал, нажать кнопку "Изменить HTML"
там удалил весь код, и вставил новый, сохранил.

И надпись пропала "Технологии Blogger" которая была в шапке.

Люди как правило загружают шаблон через кнопку "Резервное копирование и восстановление"

**Comment by web-xaser** [comment]
1) Странно, сейчас загрузил через кнопку восстановления и виджета аттрибуции Blogger-а нет (собственно, и не должно его быть).
2) Описание блога по умолчанию сейчас не выводится.

**Comment by VadymVolos** [comment]
Создал новый блог чтоб проверить этот косяк, загрузил шаблон через кнопку "Резервное копирование и восстановление"

Проверил, все хорошо отображается, в шапке нет этого косяка.
Наверно он временно появился из за предыдущего шаблона.

Вопрос решен, тему закрываю.
