### ISSUE TITLE
Как вернуть стандартные комментарии 

### ISSUE THREAD

**Issue by VadymVolos** [web-xaser/postium#4]
Привет Павел!

Подскажи пожалуйста. можно ли вернуть стандартные комментарии, ибо комментарии от Дискус не нужны, а стандартные нужны.

**Comment by web-xaser** [comment]
Привет @VadymVolos.
На данный момент стандартные комментарии полностью выпилены из шаблона. Может в будущей версии верну.

**Comment by VadymVolos** [comment]
Ок, спасибо!

Можно не добавлять, просто в мануале написать как добавить самостоятельно
какой код и куда вставить чтоб появились стандартные комментарии.

**Comment by web-xaser** [comment]
К сожалению, с ними всё не так просто, слишком много зависимостей.

**Comment by web-xaser** [comment]
@VadymVolos, стандартные комментарии возвращены в шаблон. Виджет Disqus-а за ненадобностью можно удалить с вкладки "Дизайн" в панели управления.

**Comment by VadymVolos** [comment]
@web-xaser, спасибо! :+1:
